### PR TITLE
Fix getOrderbook and placeMarketOrder, implement getTradeHistory and getTradesOfOrder

### PR DESCRIPTION
**Pull request by Mik13**

### CODE REVIEW

**Comment by wmin0** [comment]
Thanks your great work!
However, the precision parameter in orderbook api should work. I'll add it back after merge this pr.

**Comment by wmin0** [comment]
v0.0.9 publish. plz check!

**Comment by Mik13** [comment]
Thanks, will try later

And sorry for the precision mistake, I did not see it in the parameters here (https://cobinhood.github.io/api-public/?http#get-order-book), but it's documented in the response

**Comment by Mik13** [comment]
0.0.11 seems fine, thanks wmin0

**Pull request merged**
